"""
render.py — fills SVG templates with real content and rasterizes to PNG.

Each function below maps a content dict to a finished image. Token names
match the __TOKEN__ placeholders in templates/*.svg exactly. If you add a
field, add it to the placeholder dict AND the SVG token, or it'll silently
stay as literal text in the output.

Templates are generated by tools/build_markup.py — edit that, not the SVGs.
They use the fonts in fonts/, which must be installed system-wide (fontconfig)
before rendering: the GitHub workflows copy them to ~/.local/share/fonts.

Two template attributes are handled here after the tokens are filled:
  data-fit="<px>"   max width of a text slot; the font shrinks until the
                    longest line fits (so a long event name never runs off)
  data-score="<color>"  a to-par score; its fill becomes <color> unless the
                    score is under par (under par keeps the template's red)
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

import cairosvg
from PIL import ImageFont

TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
FONT_DIR = os.path.join(os.path.dirname(__file__), "fonts")
IMG_SIZE = 1080  # output width; height follows the template's aspect ratio (4:5)

SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)

# font-family in the templates -> file in fonts/, used only to measure text for data-fit
FONT_FILES = {
    "Anton": "Anton-Regular.ttf",
    "Barlow Condensed SemiBold": "BarlowCondensed-SemiBold.ttf",
    "Barlow Medium": "Barlow-Medium.ttf",
    "Barlow SemiBold": "Barlow-SemiBold.ttf",
    "DM Serif Display": "DMSerifDisplay-Regular.ttf",
    "Permanent Marker": "PermanentMarker-Regular.ttf",
}
_font_cache = {}


def _measure(family: str, size: float, text: str, letter_spacing: float) -> float:
    key = (family, size)
    if key not in _font_cache:
        _font_cache[key] = ImageFont.truetype(os.path.join(FONT_DIR, FONT_FILES[family]), size)
    return _font_cache[key].getlength(text) + letter_spacing * max(len(text) - 1, 0)


def _inherited(el, parents, attr):
    while el is not None:
        if attr in el.attrib:
            return el.attrib[attr]
        el = parents.get(el)
    return None


def _apply_fit_and_score(svg: str, template_filename: str) -> str:
    root = ET.fromstring(svg)
    parents = {child: parent for parent in root.iter() for child in parent}
    for el in root.iter():
        score_fill = el.attrib.get("data-score")
        if score_fill is not None and not (el.text or "").strip().startswith(("-", "−")):
            el.set("fill", score_fill)

        max_width = el.attrib.get("data-fit")
        if max_width is None:
            continue
        family = _inherited(el, parents, "font-family")
        if family not in FONT_FILES:
            print(f"render.py: no font file for {family!r} in {template_filename}; skipping auto-fit", file=sys.stderr)
            continue
        size = float(_inherited(el, parents, "font-size"))
        spacing = float(_inherited(el, parents, "letter-spacing") or 0)
        lines = [el.text or ""] + [t.text or "" for t in el if t.tag == f"{{{SVG_NS}}}tspan"]
        widest = max(_measure(family, size, line, spacing) for line in lines)
        limit = float(max_width) * 0.99  # small margin: PIL and cairo measure a hair differently
        if widest > limit:
            factor = limit / widest       # shrink size AND letter-spacing, or long spaced text still overflows
            el.set("font-size", f"{size * factor:.1f}")
            if spacing:
                el.set("letter-spacing", f"{spacing * factor:.2f}")
    return ET.tostring(root, encoding="unicode")


def _fill_and_render(template_filename: str, tokens: dict, out_path: str, raw_tokens: dict = None) -> str:
    """Loads an SVG template, replaces __TOKEN__ placeholders, fits text, rasterizes to PNG.
    raw_tokens are SVG fragments we generate ourselves (inserted unescaped)."""
    path = os.path.join(TEMPLATE_DIR, template_filename)
    with open(path, "r", encoding="utf-8") as f:
        svg = f.read()

    for key, value in (raw_tokens or {}).items():
        token = f"__{key.upper()}__"
        if token not in svg:
            raise ValueError(f"Token {token} not found in {template_filename} — check spelling.")
        svg = svg.replace(token, value)
    for key, value in tokens.items():
        token = f"__{key.upper()}__"
        if token not in svg:
            raise ValueError(f"Token {token} not found in {template_filename} — check spelling.")
        svg = svg.replace(token, _escape_xml(str(value)))

    # catch any tokens that were left unfilled (would render as literal "__X__" text)
    leftover = re.findall(r"__[A-Z0-9_]+__", svg)
    if leftover:
        raise ValueError(f"Unfilled tokens in {template_filename}: {set(leftover)}")

    svg = _apply_fit_and_score(svg, template_filename)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    cairosvg.svg2png(bytestring=svg.encode("utf-8"), write_to=out_path,
                      output_width=IMG_SIZE)
    return out_path


def _escape_xml(text: str) -> str:
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def render_leaderboard(event: str, round_label: str, players: list, out_path: str) -> str:
    """players: up to 5 dicts like {"name": "Scottie Scheffler", "score": "-12", "pos": "T2"}.
    "pos" is optional (defaults to 1-5); pass real positions so ties show as T2."""
    n = len(players[:5])
    players = (players[:5] + [{"name": "", "score": "", "pos": ""}] * 5)[:5]
    tokens = {"event": event, "round": round_label}
    for i, p in enumerate(players, start=1):
        tokens[f"pos_{i}"] = p.get("pos", str(i) if i <= n else "")
        tokens[f"player_{i}"] = p.get("name", "")
        tokens[f"score_{i}"] = p.get("score", "")
    return _fill_and_render("leaderboard.svg", tokens, out_path)


def render_hot_take(lines: list, kicker: str, out_path: str) -> str:
    """lines: up to 4 strings, one per line of the big bold quote block."""
    lines = (lines + [""] * 4)[:4]
    tokens = {f"take_line_{i+1}": line for i, line in enumerate(lines)}
    tokens["kicker"] = kicker
    return _fill_and_render("hot_take.svg", tokens, out_path)


def render_weekly_picks(event_name: str, win: str, value: str, fade: str, sleeper: str, out_path: str) -> str:
    tokens = {
        "event_name": event_name, "win_player": win, "value_player": value,
        "fade_player": fade, "sleeper_player": sleeper,
    }
    return _fill_and_render("weekly_picks.svg", tokens, out_path)


def render_intel_stat(stat: str, what_it_means: str, supporting_line: str, out_path: str) -> str:
    tokens = {"stat": stat, "what_it_means": what_it_means, "supporting_line": supporting_line}
    return _fill_and_render("intel_stat.svg", tokens, out_path)


def render_live_alert(hole_moment: str, event_line_1: str, event_line_2: str, reaction: str, out_path: str,
                      scorecard: dict = None) -> str:
    """scorecard: {"holes": [9], "pars": [int|None], "rel": [int|None]} (transform.alert_scorecard); the strip
    marks birdies/eagles/bogeys/doubles in Sharpie. Without one, a blank 1-9 strip."""
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools"))
    from scorecard_strip import strip
    sc = scorecard or {"holes": list(range(1, 10)), "pars": [None] * 9, "rel": [None] * 9}
    tokens = {
        "hole_moment": hole_moment, "event_line_1": event_line_1,
        "event_line_2": event_line_2, "reaction": reaction,
    }
    return _fill_and_render("live_alert.svg", tokens, out_path,
                            raw_tokens={"scorecard": strip(1000, sc["holes"], sc["pars"], sc["rel"])})



def render_pick_detail(slot: str, player: str, event: str, model_win: str, books_win: str, odds: str,
                       skills: dict, note: str, out_path: str) -> str:
    """Carousel slide for one pick. slot: win/value/fade/sleeper (picks the Sharpie mark).
    skills: {"OTT"|"APP"|"ARG"|"PUTT": ("+0.45", "#12")}; missing keys render as em dashes."""
    tokens = {"player": player, "event": event, "model_win": model_win, "books_win": books_win,
              "odds": odds, "note": note}
    for key in ("OTT", "APP", "ARG", "PUTT"):
        value, rank = skills.get(key, ("—", "—"))
        tokens[f"sg_{key}"] = value
        tokens[f"rank_{key}"] = rank
    return _fill_and_render(f"pick_{slot}.svg", tokens, out_path)


def render_stat_list(title: str, subtitle: str, header: str, rows: list, note: str, out_path: str,
                     kicker: str = "THIS WEEK'S CARD") -> str:
    """Carousel top-5 list. rows: up to 5 (name, value) pairs; the top value gets the Sharpie circle."""
    rows = (list(rows)[:5] + [("", "")] * 5)[:5]
    tokens = {"title": title, "subtitle": subtitle, "header": header, "note": note, "kicker": kicker}
    for i, (name, value) in enumerate(rows, start=1):
        tokens[f"name_{i}"] = name
        tokens[f"value_{i}"] = value
    return _fill_and_render("stat_list.svg", tokens, out_path)


def render_round_wrap(title: str, subtitle: str, leader: str, leader_score: str, picks: list, note: str,
                      out_path: str) -> str:
    """'After Round N' card: leader banner + our four picks' position and score.
    picks: 4 (name, pos, to_par) tuples in WIN, VALUE, FADE, SLEEPER order."""
    tokens = {"title": title, "subtitle": subtitle, "leader": leader, "leader_score": leader_score, "note": note}
    for i, (name, pos, score) in enumerate((list(picks) + [("", "", "")] * 4)[:4], start=1):
        tokens[f"name_{i}"], tokens[f"pos_{i}"], tokens[f"score_{i}"] = name, pos, score
    return _fill_and_render("round_wrap.svg", tokens, out_path)


def render_round_of_day(player: str, subtitle: str, today: str, standing: str, front: dict, back: dict, note: str,
                        out_path: str) -> str:
    """Recap-carousel slide: the low round with both nines (transform.round_of_day), Sharpie scoring marks."""
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools"))
    from scorecard_strip import strip
    cards = strip(640, front["holes"], front["pars"], front["rel"]) + strip(830, back["holes"], back["pars"], back["rel"])
    return _fill_and_render("round_of_day.svg", {"player": player, "subtitle": subtitle, "today": today,
                                                 "standing": standing, "note": note}, out_path,
                            raw_tokens={"scorecard": cards})


def render_closer(event: str, out_path: str) -> str:
    """Carousel closing slide ("RECEIPTS SUNDAY.")."""
    return _fill_and_render("closer.svg", {"event": event}, out_path)


SLOT_TEMPLATES = {"win": "card_win", "value": "card_value", "fade": "card_fade", "sleeper": "card_sleeper"}
CARD_BOX = (100, 59, 980, 1291)   # the 5:7 card's bounds on the 1080x1350 slide (see tools/build_markup.py)


def _photo_data_uri(photo_path: str, style: str) -> str:
    """Library photo (already cropped to the card window) as a JPEG data: URI; style "brand" = duotone
    in the card inks so photos from different sources read as one deck."""
    import base64
    import io
    from PIL import Image, ImageEnhance, ImageOps
    im = Image.open(photo_path).convert("RGB")
    if style == "brand":
        g = ImageOps.autocontrast(ImageOps.grayscale(im), cutoff=1)
        im = ImageEnhance.Contrast(ImageOps.colorize(g, black="#1E2A22", white="#F2ECDC", mid="#7E8A70")).enhance(1.08)
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=86)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()


def render_playing_card(slot: str, player: str, event: str, model_win: str, books_win: str, odds: str,
                        skills: dict, note: str, out_path: str, photo_path: str = None, credit: str = "",
                        style: str = "color") -> str:
    """Carousel playing card for one pick. With photo_path (from tools/player_photos.lookup) the photo fills
    the window with its credit; without one, the player's initials do. style: "color" or "brand"."""
    tokens = {"player": player, "event": event, "model_win": model_win, "books_win": books_win,
              "odds": odds, "note": note}
    for key in ("OTT", "APP", "ARG", "PUTT"):
        value, rank = skills.get(key, ("—", "—"))
        tokens[f"sg_{key}"] = value
        tokens[f"rank_{key}"] = rank
    if photo_path:
        tokens["photo"] = _photo_data_uri(photo_path, style)
        tokens["credit"] = credit
        template = f"{SLOT_TEMPLATES[slot]}.svg"
    else:
        tokens["initials"] = "".join(part[0] for part in player.replace(".", " ").split() if part[:1].isalpha())[:3].upper()
        template = f"{SLOT_TEMPLATES[slot]}_nophoto.svg"
    return _fill_and_render(template, tokens, out_path)


def render_hand(card_paths: list, event: str, out_path: str, kicker: str = "swipe for the reads") -> str:
    """'This Week's Hand' cover: the rendered playing cards cut out and fanned like a poker hand.
    kicker: the marker line at the bottom ("swipe for the reads" on the carousel, something else on the Reel)."""
    import io
    from PIL import Image, ImageDraw
    bg_path = out_path + ".bg.png"
    _fill_and_render("hand_cover.svg", {"event": event, "kicker": kicker}, bg_path)
    bg = Image.open(bg_path).convert("RGBA")
    os.remove(bg_path)
    scale = bg.width / 1080
    box = tuple(int(v * scale) for v in CARD_BOX)
    n = len(card_paths)
    angles = [-15, -5, 5, 15][:n] if n == 4 else [(-15 + 30 * i / max(n - 1, 1)) for i in range(n)]
    xs = [330, 470, 610, 750][:n] if n == 4 else [int(330 + 420 * i / max(n - 1, 1)) for i in range(n)]
    for path, angle, x in zip(card_paths, angles, xs):
        card = Image.open(path).convert("RGBA").crop(box)
        mask = Image.new("L", card.size, 0)
        ImageDraw.Draw(mask).rounded_rectangle((0, 0, card.width - 1, card.height - 1), radius=int(40 * scale), fill=255)
        card.putalpha(mask)
        card = card.resize((int(400 * scale), int(560 * scale)), Image.LANCZOS)
        rotated = card.rotate(-angle, expand=True, resample=Image.BICUBIC)
        bg.alpha_composite(rotated, (int(x * scale) - rotated.width // 2, int((340 + abs(angle) * 3) * scale)))
    bg.convert("RGB").save(out_path)
    return out_path


def render_reel(slides: list, out_path: str, fps: int = 30, audio: str = None) -> str:
    """Vertical 1080x1920 Reel (H.264). Silent unless `audio` (a clip file) is given: then it's laid under
    the video, cut to the video's length with a 1.5 s fade-out (otherwise music is added in the app).
    slides: [{"path": 4:5 png, "seconds": float, "top": heading, "sub": one-line meaning, "bottom": why line}]
    (text keys optional; "deal": seconds for the card's entrance, default a quick 7-frame snap; "zoom": push-in
    amount, default 0.02; "hook": big opening line that fades in, holds and fades out over "hook_seconds"
    (default 1.9: 0.45 s fades, 1 s hold) before the card slides in; "closer": a red marker line written
    on its own screen after the card, large and tilted with a snaking underline, over "closer_seconds"
    (default 2.6); "zoom_seconds": reach the full push-in this fast, then hold; "exit": seconds to slide out left). Each card is
    "dealt" in: a snap with a small settling rotation, then a slow
    push-in; text sits above/below the card, inside Instagram's safe area. Hard cuts, no cross-fade. Needs ffmpeg."""
    import shutil
    import subprocess
    from PIL import Image, ImageDraw, ImageFont
    if not shutil.which("ffmpeg"):
        raise RuntimeError("ffmpeg not installed; can't build the Reel")
    W, H = 1080, 1920
    PAPER, INK, RED, PENCIL = (0xF2, 0xEC, 0xDC), (0x1E, 0x2A, 0x22), (0xD3, 0x26, 0x1F), (0x6E, 0x68, 0x57)
    CARD_W, CARD_TOP = 900, 400                      # card 900x1125, y 400-1525; text 250-385 and 1550-1640
    font = lambda fam, size: ImageFont.truetype(os.path.join(FONT_DIR, FONT_FILES[fam]), size)

    def fit(draw, text, fam, size, max_w):
        while size > 18 and draw.textlength(text, font=font(fam, size)) > max_w:
            size -= 2
        return font(fam, size)

    def background(sl):
        bg = Image.new("RGB", (W, H), PAPER)
        d = ImageDraw.Draw(bg)
        if sl.get("top"):
            f = fit(d, sl["top"], "Anton", 76, 960)
            d.text((W // 2, 285), sl["top"], font=f, fill=INK, anchor="mm")
        if sl.get("sub"):
            f = fit(d, sl["sub"], "Barlow SemiBold", 36, 960)
            d.text((W // 2, 352), sl["sub"], font=f, fill=PENCIL, anchor="mm")
        if sl.get("bottom"):
            f = fit(d, sl["bottom"], "Permanent Marker", 44, 960)
            d.text((W // 2, 1600), sl["bottom"], font=f, fill=RED, anchor="mm")
        return bg

    def closer_frames(text, total):
        """Large red marker line at a tilt, written on left to right, then a snaking underline drawn the same
        way, then a hold. Yields raw frames."""
        layer = Image.new("RGBA", (W, 700), (0, 0, 0, 0))
        d = ImageDraw.Draw(layer)
        words, lines = text.upper().split(), []
        f = fit(d, text.upper(), "Permanent Marker", 150, 960)
        if f.size < 110 and len(words) > 1:          # long line: two lines at a bigger size
            mid = (len(words) + 1) // 2
            lines = [" ".join(words[:mid]), " ".join(words[mid:])]
            f = fit(d, max(lines, key=lambda l: d.textlength(l, font=font("Permanent Marker", 150))),
                    "Permanent Marker", 150, 960)
        else:
            lines = [text.upper()]
        gap = int(f.size * 1.2)
        y0 = 330 - gap * (len(lines) - 1) // 2
        boxes = []
        for i, line in enumerate(lines):
            d.text((W // 2, y0 + i * gap), line, font=f, fill=RED + (255,), anchor="mm")
            boxes.append(d.textbbox((W // 2, y0 + i * gap), line, font=f, anchor="mm"))
        x0, x1 = min(b[0] for b in boxes), max(b[2] for b in boxes)
        import math
        zy, amp, wave, step = max(b[3] for b in boxes) + 45, 13, 170, 4   # smooth snake, ~170 px per wave
        zig = [(x, zy + amp * math.sin(2 * math.pi * (x - x0) / wave)) for x in range(x0, x1 + step, step)]
        write_n, zig_n = max(1, round(total * 0.4)), max(1, round(total * 0.2))
        bg = Image.new("RGB", (W, H), PAPER)
        def compose(text_upto, zig_upto):
            part = Image.new("RGBA", layer.size, (0, 0, 0, 0))
            if text_upto > x0:
                part.paste(layer.crop((0, 0, text_upto, layer.height)), (0, 0))
            if zig_upto > x0:
                pts = [pt for pt in zig if pt[0] <= zig_upto]
                if len(pts) > 1:
                    ImageDraw.Draw(part).line(pts, fill=RED + (255,), width=12, joint="curve")
            rot = part.rotate(6, expand=False, resample=Image.BICUBIC)   # tilted up to the right
            frame = bg.copy()
            frame.paste(rot, (0, H // 2 - 350), rot)
            return frame.tobytes()
        held = None
        for i in range(total):
            if i < write_n:
                yield compose(x0 + int((x1 - x0 + 30) * (i + 1) / write_n), 0)
            elif i < write_n + zig_n:
                yield compose(x1 + 30, x0 + int((x1 - x0 + step) * (i - write_n + 1) / zig_n))
            else:
                held = held or compose(x1 + 30, x1 + step)
                yield held

    def card_img(path):
        img = Image.open(path).convert("RGBA")
        return img.resize((CARD_W, int(img.height * CARD_W / img.width)), Image.LANCZOS)

    deal_frames = lambda sl: max(2, round(sl.get("deal", 7 / fps) * fps))   # entrance length per slide
    hook_frames = lambda sl: round(sl.get("hook_seconds", 1.9) * fps) if sl.get("hook") else 0

    def hook_frame(text):
        """The scroll-stopper: the hook alone, huge, up to three lines, centred."""
        bg = Image.new("RGB", (W, H), PAPER)
        d = ImageDraw.Draw(bg)
        words, size = text.upper().split(), 230
        while True:
            f = font("Anton", size)
            lines, cur = [], ""
            for w in words:
                trial = f"{cur} {w}".strip()
                if d.textlength(trial, font=f) <= 960 or not cur:
                    cur = trial
                else:
                    lines.append(cur)
                    cur = w
            lines.append(cur)
            if (len(lines) <= 3 and all(d.textlength(l, font=f) <= 960 for l in lines)) or size <= 60:
                break
            size -= 6
        gap = int(size * 1.15)
        y0 = H // 2 - gap * (len(lines) - 1) // 2
        for i, line in enumerate(lines):
            d.text((W // 2, y0 + i * gap), line, font=f, fill=INK, anchor="mm")
        d.line([(W // 2 - 220, y0 + gap * (len(lines) - 1) + int(size * 0.75)),
                (W // 2 + 220, y0 + gap * (len(lines) - 1) + int(size * 0.75))], fill=RED, width=10)
        return bg
    video_path = out_path + ".silent.mp4" if audio else out_path
    proc = subprocess.Popen(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{W}x{H}",
         "-r", str(fps), "-i", "-", "-c:v", "libx264", "-preset", "medium", "-crf", "20",
         "-pix_fmt", "yuv420p", "-movflags", "+faststart", video_path],
        stdin=subprocess.PIPE)
    try:
        for sl in slides:
            if sl.get("hook"):                       # fade in, hold, fade out, then the card slides in
                full, blank = hook_frame(sl["hook"]), Image.new("RGB", (W, H), PAPER)
                total_h, fade = hook_frames(sl), round(sl.get("hook_fade", 0.45) * fps)
                for i in range(total_h):
                    a_in = (i + 1) / fade if sl.get("hook_fade_in", True) else 1.0   # off = frame 1 is the hook
                    a = min(1.0, a_in, (total_h - i) / fade)
                    proc.stdin.write((full if a >= 1 else Image.blend(blank, full, a)).tobytes())
            bg, card = background(sl), card_img(sl["path"])
            deal = deal_frames(sl)
            zoom = sl.get("zoom", 0.02)
            n = max(int(sl.get("seconds", 1.6) * fps), deal + 1)
            exit_n = round(sl.get("exit", 0) * fps)          # slide out to the left at the end of the slide
            zoom_n = round(sl.get("zoom_seconds", 0) * fps) or max(n - exit_n - deal, 1)
            for f in range(n):
                if f < deal:                         # dealt in from fully off the right edge, settling turn
                    e = 1 - (1 - f / deal) ** 3          # frame 0 = e 0 = card entirely out of frame
                    start = W // 2 + card.width // 2 + 80   # +80 covers the rotated corner
                    angle, scale, dx = 3 * (1 - e), 1.0, int(start * (1 - e))
                else:                                # push-in, eased, done after zoom_n frames, then holds
                    angle, dx = 0.0, 0
                    p = min(1.0, (f - deal) / max(zoom_n, 1))
                    scale = 1.0 + zoom * (1 - (1 - p) ** 2)
                    k = f - (n - exit_n)
                    if exit_n and k >= 0:            # exit: accelerate off the left edge with a small turn
                        e = ((k + 1) / exit_n) ** 2
                        dx = -int((W // 2 + card.width * (1 + zoom) // 2 + 80) * e)
                        angle = -3 * e
                c = card.resize((int(card.width * scale), int(card.height * scale)), Image.BICUBIC)
                if angle:
                    c = c.rotate(angle, expand=True, resample=Image.BICUBIC)
                frame = bg.copy()
                cx, cy = W // 2 + dx, CARD_TOP + card.height // 2
                frame.paste(c, (cx - c.width // 2, cy - c.height // 2), c)
                proc.stdin.write(frame.tobytes())
            if sl.get("closer"):                     # sign-off on its own screen: big, tilted, marker-written
                for frame in closer_frames(sl["closer"], round(sl.get("closer_seconds", 2.6) * fps)):
                    proc.stdin.write(frame)
    finally:
        proc.stdin.close()
        rc = proc.wait()
    if rc != 0:
        raise RuntimeError(f"ffmpeg failed (exit {rc})")
    if audio:
        total = sum(max(int(sl.get("seconds", 1.6) * fps), deal_frames(sl) + 1) + hook_frames(sl)
                    + (round(sl.get("closer_seconds", 2.6) * fps) if sl.get("closer") else 0)
                    for sl in slides) / fps
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", video_path, "-i", audio,
                        "-map", "0:v", "-map", "1:a", "-c:v", "copy",
                        "-af", f"apad,atrim=0:{total:.3f},afade=t=out:st={max(total - 1.5, 0):.3f}:d=1.5",
                        "-c:a", "aac", "-b:a", "160k", "-ar", "48000", "-t", f"{total:.3f}",
                        "-movflags", "+faststart", out_path], check=True)
        os.remove(video_path)
    return out_path

if __name__ == "__main__":
    # smoke test with mock data
    render_leaderboard(
        event="THE OPEN", round_label="ROUND 3",
        players=[
            {"name": "Scottie Scheffler", "score": "-14"},
            {"name": "Rory McIlroy", "score": "-11"},
            {"name": "Xander Schauffele", "score": "-10"},
            {"name": "Ludvig Åberg", "score": "-9"},
            {"name": "Viktor Hovland", "score": "-8"},
        ],
        out_path=os.path.join(OUTPUT_DIR, "test_leaderboard.png"),
    )
    render_hot_take(
        lines=["SCOTTIE IS", "BORING US INTO", "SUBMISSION AND", "WE LOVE IT."],
        kicker="— a take nobody asked for, week 11 of him winning everything",
        out_path=os.path.join(OUTPUT_DIR, "test_hot_take.png"),
    )
    render_weekly_picks(
        event_name="THE OPEN CHAMPIONSHIP",
        win="Scottie Scheffler", value="Tommy Fleetwood",
        fade="Jon Rahm", sleeper="Akshay Bhatia",
        out_path=os.path.join(OUTPUT_DIR, "test_weekly_picks.png"),
    )
    render_intel_stat(
        stat="0.41", what_it_means="SCHEFFLER'S SG: APPROACH THIS SEASON",
        supporting_line="best mark on tour by a country mile",
        out_path=os.path.join(OUTPUT_DIR, "test_intel_stat.png"),
    )
    render_live_alert(
        hole_moment="HOLE 17 · R4", event_line_1="ALBATROSS ON",
        event_line_2="THE PAR 5.", reaction="...we need to talk about this round.",
        out_path=os.path.join(OUTPUT_DIR, "test_live_alert.png"),
    )
    print("All 5 templates rendered successfully.")
