"""
render.py — fills SVG templates with real content and rasterizes to PNG.

Each function below maps a content dict to a finished image. Token names
match the __TOKEN__ placeholders in templates/*.svg exactly. If you add a
field, add it to the placeholder dict AND the SVG token, or it'll silently
stay as literal text in the output.

Templates are generated by tools/build_markup.py — edit that, not the SVGs.
They use the fonts in fonts/, which must be installed system-wide (fontconfig)
before rendering: the GitHub workflows copy them to ~/.local/share/fonts.

Two template attributes are handled here after the tokens are filled:
  data-fit="<px>"   max width of a text slot; the font shrinks until the
                    longest line fits (so a long event name never runs off)
  data-score="<color>"  a to-par score; its fill becomes <color> unless the
                    score is under par (under par keeps the template's red)
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

import cairosvg
from PIL import ImageFont

TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
FONT_DIR = os.path.join(os.path.dirname(__file__), "fonts")
IMG_SIZE = 1080  # output width; height follows the template's aspect ratio (4:5)

SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)

# font-family in the templates -> file in fonts/, used only to measure text for data-fit
FONT_FILES = {
    "Anton": "Anton-Regular.ttf",
    "Barlow Condensed SemiBold": "BarlowCondensed-SemiBold.ttf",
    "Barlow Medium": "Barlow-Medium.ttf",
    "Barlow SemiBold": "Barlow-SemiBold.ttf",
    "DM Serif Display": "DMSerifDisplay-Regular.ttf",
    "Permanent Marker": "PermanentMarker-Regular.ttf",
}
_font_cache = {}


def _measure(family: str, size: float, text: str, letter_spacing: float) -> float:
    key = (family, size)
    if key not in _font_cache:
        _font_cache[key] = ImageFont.truetype(os.path.join(FONT_DIR, FONT_FILES[family]), size)
    return _font_cache[key].getlength(text) + letter_spacing * max(len(text) - 1, 0)


def _inherited(el, parents, attr):
    while el is not None:
        if attr in el.attrib:
            return el.attrib[attr]
        el = parents.get(el)
    return None


def _apply_fit_and_score(svg: str, template_filename: str) -> str:
    root = ET.fromstring(svg)
    parents = {child: parent for parent in root.iter() for child in parent}
    for el in root.iter():
        score_fill = el.attrib.get("data-score")
        if score_fill is not None and not (el.text or "").strip().startswith(("-", "−")):
            el.set("fill", score_fill)

        max_width = el.attrib.get("data-fit")
        if max_width is None:
            continue
        family = _inherited(el, parents, "font-family")
        if family not in FONT_FILES:
            print(f"render.py: no font file for {family!r} in {template_filename}; skipping auto-fit", file=sys.stderr)
            continue
        size = float(_inherited(el, parents, "font-size"))
        spacing = float(_inherited(el, parents, "letter-spacing") or 0)
        lines = [el.text or ""] + [t.text or "" for t in el if t.tag == f"{{{SVG_NS}}}tspan"]
        widest = max(_measure(family, size, line, spacing) for line in lines)
        limit = float(max_width) * 0.99  # small margin: PIL and cairo measure a hair differently
        if widest > limit:
            el.set("font-size", f"{size * limit / widest:.1f}")
    return ET.tostring(root, encoding="unicode")


def _fill_and_render(template_filename: str, tokens: dict, out_path: str) -> str:
    """Loads an SVG template, replaces __TOKEN__ placeholders, fits text, rasterizes to PNG."""
    path = os.path.join(TEMPLATE_DIR, template_filename)
    with open(path, "r", encoding="utf-8") as f:
        svg = f.read()

    for key, value in tokens.items():
        token = f"__{key.upper()}__"
        if token not in svg:
            raise ValueError(f"Token {token} not found in {template_filename} — check spelling.")
        svg = svg.replace(token, _escape_xml(str(value)))

    # catch any tokens that were left unfilled (would render as literal "__X__" text)
    leftover = re.findall(r"__[A-Z0-9_]+__", svg)
    if leftover:
        raise ValueError(f"Unfilled tokens in {template_filename}: {set(leftover)}")

    svg = _apply_fit_and_score(svg, template_filename)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    cairosvg.svg2png(bytestring=svg.encode("utf-8"), write_to=out_path,
                      output_width=IMG_SIZE)
    return out_path


def _escape_xml(text: str) -> str:
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def render_leaderboard(event: str, round_label: str, players: list, out_path: str) -> str:
    """players: list of up to 5 dicts like {"name": "Scottie Scheffler", "score": "-12"}"""
    players = (players + [{"name": "", "score": ""}] * 5)[:5]
    tokens = {"event": event, "round": round_label}
    for i, p in enumerate(players, start=1):
        tokens[f"player_{i}"] = p.get("name", "")
        tokens[f"score_{i}"] = p.get("score", "")
    return _fill_and_render("leaderboard.svg", tokens, out_path)


def render_hot_take(lines: list, kicker: str, out_path: str) -> str:
    """lines: up to 4 strings, one per line of the big bold quote block."""
    lines = (lines + [""] * 4)[:4]
    tokens = {f"take_line_{i+1}": line for i, line in enumerate(lines)}
    tokens["kicker"] = kicker
    return _fill_and_render("hot_take.svg", tokens, out_path)


def render_weekly_picks(event_name: str, win: str, value: str, fade: str, sleeper: str, out_path: str) -> str:
    tokens = {
        "event_name": event_name, "win_player": win, "value_player": value,
        "fade_player": fade, "sleeper_player": sleeper,
    }
    return _fill_and_render("weekly_picks.svg", tokens, out_path)


def render_intel_stat(stat: str, what_it_means: str, supporting_line: str, out_path: str) -> str:
    tokens = {"stat": stat, "what_it_means": what_it_means, "supporting_line": supporting_line}
    return _fill_and_render("intel_stat.svg", tokens, out_path)


def render_live_alert(hole_moment: str, event_line_1: str, event_line_2: str, reaction: str, out_path: str) -> str:
    tokens = {
        "hole_moment": hole_moment, "event_line_1": event_line_1,
        "event_line_2": event_line_2, "reaction": reaction,
    }
    return _fill_and_render("live_alert.svg", tokens, out_path)


if __name__ == "__main__":
    # smoke test with mock data
    render_leaderboard(
        event="THE OPEN", round_label="ROUND 3",
        players=[
            {"name": "Scottie Scheffler", "score": "-14"},
            {"name": "Rory McIlroy", "score": "-11"},
            {"name": "Xander Schauffele", "score": "-10"},
            {"name": "Ludvig Åberg", "score": "-9"},
            {"name": "Viktor Hovland", "score": "-8"},
        ],
        out_path=os.path.join(OUTPUT_DIR, "test_leaderboard.png"),
    )
    render_hot_take(
        lines=["SCOTTIE IS", "BORING US INTO", "SUBMISSION AND", "WE LOVE IT."],
        kicker="— a take nobody asked for, week 11 of him winning everything",
        out_path=os.path.join(OUTPUT_DIR, "test_hot_take.png"),
    )
    render_weekly_picks(
        event_name="THE OPEN CHAMPIONSHIP",
        win="Scottie Scheffler", value="Tommy Fleetwood",
        fade="Jon Rahm", sleeper="Akshay Bhatia",
        out_path=os.path.join(OUTPUT_DIR, "test_weekly_picks.png"),
    )
    render_intel_stat(
        stat="0.41", what_it_means="SCHEFFLER'S SG: APPROACH THIS SEASON",
        supporting_line="best mark on tour by a country mile",
        out_path=os.path.join(OUTPUT_DIR, "test_intel_stat.png"),
    )
    render_live_alert(
        hole_moment="HOLE 17 · R4", event_line_1="ALBATROSS ON",
        event_line_2="THE PAR 5.", reaction="...we need to talk about this round.",
        out_path=os.path.join(OUTPUT_DIR, "test_live_alert.png"),
    )
    print("All 5 templates rendered successfully.")
