"""
render.py — fills SVG templates with real content and rasterizes to PNG.

Each function below maps a content dict to a finished image. Token names
match the __TOKEN__ placeholders in templates/*.svg exactly. If you add a
field, add it to the placeholder dict AND the SVG token, or it'll silently
stay as literal text in the output.

Templates are generated by tools/build_markup.py — edit that, not the SVGs.
They use the fonts in fonts/, which must be installed system-wide (fontconfig)
before rendering: the GitHub workflows copy them to ~/.local/share/fonts.

Two template attributes are handled here after the tokens are filled:
  data-fit="<px>"   max width of a text slot; the font shrinks until the
                    longest line fits (so a long event name never runs off)
  data-score="<color>"  a to-par score; its fill becomes <color> unless the
                    score is under par (under par keeps the template's red)
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

import cairosvg
from PIL import ImageFont

TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
FONT_DIR = os.path.join(os.path.dirname(__file__), "fonts")
IMG_SIZE = 1080  # output width; height follows the template's aspect ratio (4:5)

SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)

# font-family in the templates -> file in fonts/, used only to measure text for data-fit
FONT_FILES = {
    "Anton": "Anton-Regular.ttf",
    "Barlow Condensed SemiBold": "BarlowCondensed-SemiBold.ttf",
    "Barlow Medium": "Barlow-Medium.ttf",
    "Barlow SemiBold": "Barlow-SemiBold.ttf",
    "DM Serif Display": "DMSerifDisplay-Regular.ttf",
    "Permanent Marker": "PermanentMarker-Regular.ttf",
}
_font_cache = {}


def _measure(family: str, size: float, text: str, letter_spacing: float) -> float:
    key = (family, size)
    if key not in _font_cache:
        _font_cache[key] = ImageFont.truetype(os.path.join(FONT_DIR, FONT_FILES[family]), size)
    return _font_cache[key].getlength(text) + letter_spacing * max(len(text) - 1, 0)


def _inherited(el, parents, attr):
    while el is not None:
        if attr in el.attrib:
            return el.attrib[attr]
        el = parents.get(el)
    return None


def _apply_fit_and_score(svg: str, template_filename: str) -> str:
    root = ET.fromstring(svg)
    parents = {child: parent for parent in root.iter() for child in parent}
    for el in root.iter():
        score_fill = el.attrib.get("data-score")
        if score_fill is not None and not (el.text or "").strip().startswith(("-", "−")):
            el.set("fill", score_fill)

        max_width = el.attrib.get("data-fit")
        if max_width is None:
            continue
        family = _inherited(el, parents, "font-family")
        if family not in FONT_FILES:
            print(f"render.py: no font file for {family!r} in {template_filename}; skipping auto-fit", file=sys.stderr)
            continue
        size = float(_inherited(el, parents, "font-size"))
        spacing = float(_inherited(el, parents, "letter-spacing") or 0)
        lines = [el.text or ""] + [t.text or "" for t in el if t.tag == f"{{{SVG_NS}}}tspan"]
        widest = max(_measure(family, size, line, spacing) for line in lines)
        limit = float(max_width) * 0.99  # small margin: PIL and cairo measure a hair differently
        if widest > limit:
            el.set("font-size", f"{size * limit / widest:.1f}")
    return ET.tostring(root, encoding="unicode")


def _fill_and_render(template_filename: str, tokens: dict, out_path: str) -> str:
    """Loads an SVG template, replaces __TOKEN__ placeholders, fits text, rasterizes to PNG."""
    path = os.path.join(TEMPLATE_DIR, template_filename)
    with open(path, "r", encoding="utf-8") as f:
        svg = f.read()

    for key, value in tokens.items():
        token = f"__{key.upper()}__"
        if token not in svg:
            raise ValueError(f"Token {token} not found in {template_filename} — check spelling.")
        svg = svg.replace(token, _escape_xml(str(value)))

    # catch any tokens that were left unfilled (would render as literal "__X__" text)
    leftover = re.findall(r"__[A-Z0-9_]+__", svg)
    if leftover:
        raise ValueError(f"Unfilled tokens in {template_filename}: {set(leftover)}")

    svg = _apply_fit_and_score(svg, template_filename)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    cairosvg.svg2png(bytestring=svg.encode("utf-8"), write_to=out_path,
                      output_width=IMG_SIZE)
    return out_path


def _escape_xml(text: str) -> str:
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def render_leaderboard(event: str, round_label: str, players: list, out_path: str) -> str:
    """players: up to 5 dicts like {"name": "Scottie Scheffler", "score": "-12", "pos": "T2"}.
    "pos" is optional (defaults to 1-5); pass real positions so ties show as T2."""
    n = len(players[:5])
    players = (players[:5] + [{"name": "", "score": "", "pos": ""}] * 5)[:5]
    tokens = {"event": event, "round": round_label}
    for i, p in enumerate(players, start=1):
        tokens[f"pos_{i}"] = p.get("pos", str(i) if i <= n else "")
        tokens[f"player_{i}"] = p.get("name", "")
        tokens[f"score_{i}"] = p.get("score", "")
    return _fill_and_render("leaderboard.svg", tokens, out_path)


def render_hot_take(lines: list, kicker: str, out_path: str) -> str:
    """lines: up to 4 strings, one per line of the big bold quote block."""
    lines = (lines + [""] * 4)[:4]
    tokens = {f"take_line_{i+1}": line for i, line in enumerate(lines)}
    tokens["kicker"] = kicker
    return _fill_and_render("hot_take.svg", tokens, out_path)


def render_weekly_picks(event_name: str, win: str, value: str, fade: str, sleeper: str, out_path: str) -> str:
    tokens = {
        "event_name": event_name, "win_player": win, "value_player": value,
        "fade_player": fade, "sleeper_player": sleeper,
    }
    return _fill_and_render("weekly_picks.svg", tokens, out_path)


def render_intel_stat(stat: str, what_it_means: str, supporting_line: str, out_path: str) -> str:
    tokens = {"stat": stat, "what_it_means": what_it_means, "supporting_line": supporting_line}
    return _fill_and_render("intel_stat.svg", tokens, out_path)


def render_live_alert(hole_moment: str, event_line_1: str, event_line_2: str, reaction: str, out_path: str) -> str:
    tokens = {
        "hole_moment": hole_moment, "event_line_1": event_line_1,
        "event_line_2": event_line_2, "reaction": reaction,
    }
    return _fill_and_render("live_alert.svg", tokens, out_path)



def render_pick_detail(slot: str, player: str, event: str, model_win: str, books_win: str, odds: str,
                       skills: dict, note: str, out_path: str) -> str:
    """Carousel slide for one pick. slot: win/value/fade/sleeper (picks the Sharpie mark).
    skills: {"OTT"|"APP"|"ARG"|"PUTT": ("+0.45", "#12")}; missing keys render as em dashes."""
    tokens = {"player": player, "event": event, "model_win": model_win, "books_win": books_win,
              "odds": odds, "note": note}
    for key in ("OTT", "APP", "ARG", "PUTT"):
        value, rank = skills.get(key, ("—", "—"))
        tokens[f"sg_{key}"] = value
        tokens[f"rank_{key}"] = rank
    return _fill_and_render(f"pick_{slot}.svg", tokens, out_path)


def render_stat_list(title: str, subtitle: str, header: str, rows: list, note: str, out_path: str) -> str:
    """Carousel top-5 list. rows: up to 5 (name, value) pairs; the top value gets the Sharpie circle."""
    rows = (list(rows)[:5] + [("", "")] * 5)[:5]
    tokens = {"title": title, "subtitle": subtitle, "header": header, "note": note}
    for i, (name, value) in enumerate(rows, start=1):
        tokens[f"name_{i}"] = name
        tokens[f"value_{i}"] = value
    return _fill_and_render("stat_list.svg", tokens, out_path)


def render_closer(event: str, out_path: str) -> str:
    """Carousel closing slide ("RECEIPTS SUNDAY.")."""
    return _fill_and_render("closer.svg", {"event": event}, out_path)


SLOT_TEMPLATES = {"win": "card_win", "value": "card_value", "fade": "card_fade", "sleeper": "card_sleeper"}
CARD_BOX = (100, 59, 980, 1291)   # the 5:7 card's bounds on the 1080x1350 slide (see tools/build_markup.py)


def _photo_data_uri(photo_path: str, style: str) -> str:
    """Library photo (already cropped to the card window) as a JPEG data: URI; style "brand" = duotone
    in the card inks so photos from different sources read as one deck."""
    import base64
    import io
    from PIL import Image, ImageEnhance, ImageOps
    im = Image.open(photo_path).convert("RGB")
    if style == "brand":
        g = ImageOps.autocontrast(ImageOps.grayscale(im), cutoff=1)
        im = ImageEnhance.Contrast(ImageOps.colorize(g, black="#1E2A22", white="#F2ECDC", mid="#7E8A70")).enhance(1.08)
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=86)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()


def render_playing_card(slot: str, player: str, event: str, model_win: str, books_win: str, odds: str,
                        skills: dict, note: str, out_path: str, photo_path: str = None, credit: str = "",
                        style: str = "color") -> str:
    """Carousel playing card for one pick. With photo_path (from tools/player_photos.lookup) the photo fills
    the window with its credit; without one, the player's initials do. style: "color" or "brand"."""
    tokens = {"player": player, "event": event, "model_win": model_win, "books_win": books_win,
              "odds": odds, "note": note}
    for key in ("OTT", "APP", "ARG", "PUTT"):
        value, rank = skills.get(key, ("—", "—"))
        tokens[f"sg_{key}"] = value
        tokens[f"rank_{key}"] = rank
    if photo_path:
        tokens["photo"] = _photo_data_uri(photo_path, style)
        tokens["credit"] = credit
        template = f"{SLOT_TEMPLATES[slot]}.svg"
    else:
        tokens["initials"] = "".join(part[0] for part in player.replace(".", " ").split() if part[:1].isalpha())[:3].upper()
        template = f"{SLOT_TEMPLATES[slot]}_nophoto.svg"
    return _fill_and_render(template, tokens, out_path)


def render_hand(card_paths: list, event: str, out_path: str) -> str:
    """'This Week's Hand' cover: the rendered playing cards cut out and fanned like a poker hand."""
    import io
    from PIL import Image, ImageDraw
    bg_path = out_path + ".bg.png"
    _fill_and_render("hand_cover.svg", {"event": event}, bg_path)
    bg = Image.open(bg_path).convert("RGBA")
    os.remove(bg_path)
    scale = bg.width / 1080
    box = tuple(int(v * scale) for v in CARD_BOX)
    n = len(card_paths)
    angles = [-15, -5, 5, 15][:n] if n == 4 else [(-15 + 30 * i / max(n - 1, 1)) for i in range(n)]
    xs = [330, 470, 610, 750][:n] if n == 4 else [int(330 + 420 * i / max(n - 1, 1)) for i in range(n)]
    for path, angle, x in zip(card_paths, angles, xs):
        card = Image.open(path).convert("RGBA").crop(box)
        mask = Image.new("L", card.size, 0)
        ImageDraw.Draw(mask).rounded_rectangle((0, 0, card.width - 1, card.height - 1), radius=int(40 * scale), fill=255)
        card.putalpha(mask)
        card = card.resize((int(400 * scale), int(560 * scale)), Image.LANCZOS)
        rotated = card.rotate(-angle, expand=True, resample=Image.BICUBIC)
        bg.alpha_composite(rotated, (int(x * scale) - rotated.width // 2, int((340 + abs(angle) * 3) * scale)))
    bg.convert("RGB").save(out_path)
    return out_path


def render_reel(slides: list, out_path: str, fps: int = 30) -> str:
    """Vertical 1080x1920 Reel (H.264, silent; music is added in the Instagram app).
    slides: [{"path": 4:5 png, "seconds": float, "top": heading, "sub": one-line meaning, "bottom": why line}]
    (text keys optional). Each card is "dealt" in: a quick snap with a small settling rotation, then a slow
    push-in; text sits above/below the card, inside Instagram's safe area. Hard cuts, no cross-fade. Needs ffmpeg."""
    import shutil
    import subprocess
    from PIL import Image, ImageDraw, ImageFont
    if not shutil.which("ffmpeg"):
        raise RuntimeError("ffmpeg not installed; can't build the Reel")
    W, H = 1080, 1920
    PAPER, INK, RED, PENCIL = (0xF2, 0xEC, 0xDC), (0x1E, 0x2A, 0x22), (0xD3, 0x26, 0x1F), (0x6E, 0x68, 0x57)
    CARD_W, CARD_TOP = 900, 400                      # card 900x1125, y 400-1525; text 250-385 and 1550-1640
    font = lambda fam, size: ImageFont.truetype(os.path.join(FONT_DIR, FONT_FILES[fam]), size)

    def fit(draw, text, fam, size, max_w):
        while size > 18 and draw.textlength(text, font=font(fam, size)) > max_w:
            size -= 2
        return font(fam, size)

    def background(sl):
        bg = Image.new("RGB", (W, H), PAPER)
        d = ImageDraw.Draw(bg)
        if sl.get("top"):
            f = fit(d, sl["top"], "Anton", 76, 960)
            d.text((W // 2, 285), sl["top"], font=f, fill=INK, anchor="mm")
        if sl.get("sub"):
            f = fit(d, sl["sub"], "Barlow SemiBold", 36, 960)
            d.text((W // 2, 352), sl["sub"], font=f, fill=PENCIL, anchor="mm")
        if sl.get("bottom"):
            f = fit(d, sl["bottom"], "Permanent Marker", 44, 960)
            d.text((W // 2, 1600), sl["bottom"], font=f, fill=RED, anchor="mm")
        return bg

    def card_img(path):
        img = Image.open(path).convert("RGBA")
        return img.resize((CARD_W, int(img.height * CARD_W / img.width)), Image.LANCZOS)

    deal = 7                                         # frames for the snap-in
    proc = subprocess.Popen(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{W}x{H}",
         "-r", str(fps), "-i", "-", "-c:v", "libx264", "-preset", "medium", "-crf", "20",
         "-pix_fmt", "yuv420p", "-movflags", "+faststart", out_path],
        stdin=subprocess.PIPE)
    try:
        for sl in slides:
            bg, card = background(sl), card_img(sl["path"])
            n = max(int(sl.get("seconds", 1.6) * fps), deal + 1)
            for f in range(n):
                if f < deal:                         # dealt in from the right with a small settling turn
                    e = 1 - (1 - (f + 1) / deal) ** 3
                    angle, scale, dx = 3 * (1 - e), 1.0, int(420 * (1 - e))
                else:                                # slow push-in
                    angle, dx = 0.0, 0
                    scale = 1.0 + 0.02 * (f - deal) / max(n - deal, 1)
                c = card.resize((int(card.width * scale), int(card.height * scale)), Image.BICUBIC)
                if angle:
                    c = c.rotate(angle, expand=True, resample=Image.BICUBIC)
                frame = bg.copy()
                cx, cy = W // 2 + dx, CARD_TOP + card.height // 2
                frame.paste(c, (cx - c.width // 2, cy - c.height // 2), c)
                proc.stdin.write(frame.tobytes())
    finally:
        proc.stdin.close()
        rc = proc.wait()
    if rc != 0:
        raise RuntimeError(f"ffmpeg failed (exit {rc})")
    return out_path

if __name__ == "__main__":
    # smoke test with mock data
    render_leaderboard(
        event="THE OPEN", round_label="ROUND 3",
        players=[
            {"name": "Scottie Scheffler", "score": "-14"},
            {"name": "Rory McIlroy", "score": "-11"},
            {"name": "Xander Schauffele", "score": "-10"},
            {"name": "Ludvig Åberg", "score": "-9"},
            {"name": "Viktor Hovland", "score": "-8"},
        ],
        out_path=os.path.join(OUTPUT_DIR, "test_leaderboard.png"),
    )
    render_hot_take(
        lines=["SCOTTIE IS", "BORING US INTO", "SUBMISSION AND", "WE LOVE IT."],
        kicker="— a take nobody asked for, week 11 of him winning everything",
        out_path=os.path.join(OUTPUT_DIR, "test_hot_take.png"),
    )
    render_weekly_picks(
        event_name="THE OPEN CHAMPIONSHIP",
        win="Scottie Scheffler", value="Tommy Fleetwood",
        fade="Jon Rahm", sleeper="Akshay Bhatia",
        out_path=os.path.join(OUTPUT_DIR, "test_weekly_picks.png"),
    )
    render_intel_stat(
        stat="0.41", what_it_means="SCHEFFLER'S SG: APPROACH THIS SEASON",
        supporting_line="best mark on tour by a country mile",
        out_path=os.path.join(OUTPUT_DIR, "test_intel_stat.png"),
    )
    render_live_alert(
        hole_moment="HOLE 17 · R4", event_line_1="ALBATROSS ON",
        event_line_2="THE PAR 5.", reaction="...we need to talk about this round.",
        out_path=os.path.join(OUTPUT_DIR, "test_live_alert.png"),
    )
    print("All 5 templates rendered successfully.")
